#pragma once
#include "macros.h"

#define JCC_VERSION_NUM JCC_EXPAND_AND_STRINGIFY(JCC_VERSION_MAJOR) "." JCC_EXPAND_AND_STRINGIFY(JCC_VERSION_MINOR) "." JCC_EXPAND_AND_STRINGIFY(JCC_VERSION_PATCH)

#ifdef JCC_DEBUG
#define JCC_VERSION_SUFFIX "-debug"
#else
#define JCC_VERSION_SUFFIX ""
#endif

#define JCC_VERSION "v" JCC_VERSION_NUM JCC_VERSION_SUFFIX " (" JCC_GIT_HASH ")"