#pragma once

// Sourced from: https://stackoverflow.com/a/49272986

#define JCC_INTERFACE_TERMINAL_COLORS_GEN_FORMAT_RESET "0"
#define JCC_INTERFACE_TERMINAL_COLORS_GEN_FORMAT_BRIGHT "1"
#define JCC_INTERFACE_TERMINAL_COLORS_GEN_FORMAT_DIM "2"
#define JCC_INTERFACE_TERMINAL_COLORS_GEN_FORMAT_UNDERSCORE "3"
#define JCC_INTERFACE_TERMINAL_COLORS_GEN_FORMAT_BLINK "4"
#define JCC_INTERFACE_TERMINAL_COLORS_GEN_FORMAT_REVERSE "5"
#define JCC_INTERFACE_TERMINAL_COLORS_GEN_FORMAT_HIDDEN "6"

#define JCC_INTERFACE_TERMINAL_COLORS_FOREGROUND_COL_BLACK "30"
#define JCC_INTERFACE_TERMINAL_COLORS_FOREGROUND_COL_RED "31"
#define JCC_INTERFACE_TERMINAL_COLORS_FOREGROUND_COL_GREEN "32"
#define JCC_INTERFACE_TERMINAL_COLORS_FOREGROUND_COL_YELLOW "33"
#define JCC_INTERFACE_TERMINAL_COLORS_FOREGROUND_COL_BLUE "34"
#define JCC_INTERFACE_TERMINAL_COLORS_FOREGROUND_COL_MAGENTA "35"
#define JCC_INTERFACE_TERMINAL_COLORS_FOREGROUND_COL_CYAN "36"
#define JCC_INTERFACE_TERMINAL_COLORS_FOREGROUND_COL_WHITE "37"

#define JCC_INTERFACE_TERMINAL_COLORS_BACKGROUND_COL_BLACK "40"
#define JCC_INTERFACE_TERMINAL_COLORS_BACKGROUND_COL_RED "41"
#define JCC_INTERFACE_TERMINAL_COLORS_BACKGROUND_COL_GREEN "42"
#define JCC_INTERFACE_TERMINAL_COLORS_BACKGROUND_COL_YELLOW "43"
#define JCC_INTERFACE_TERMINAL_COLORS_BACKGROUND_COL_BLUE "44"
#define JCC_INTERFACE_TERMINAL_COLORS_BACKGROUND_COL_MAGENTA "45"
#define JCC_INTERFACE_TERMINAL_COLORS_BACKGROUND_COL_CYAN "46"
#define JCC_INTERFACE_TERMINAL_COLORS_BACKGROUND_COL_WHITE "47"

#define JCC_INTERFACE_TERMINAL_COLORS_SHELL_COLOR_ESCAPE_SEQ(X) "\x1b[" X "m"
#define JCC_INTERFACE_TERMINAL_COLORS_SHELL_FORMAT_RESET JCC_INTERFACE_TERMINAL_COLORS_SHELL_COLOR_ESCAPE_SEQ(JCC_INTERFACE_TERMINAL_COLORS_GEN_FORMAT_RESET)
